### PR TITLE
Added support for superagent@9.x.x

### PR DESCRIPTION
**Pull request by kwishna**
### Summary

This PR adds support for `superagent@9.x.x` by updating the `peerDependencies` in `package.json`.

### Changes

- Updated `peerDependencies` to include `superagent@9.x.x`
- Updated `devDependencies` versions.

### Testing

- Ran existing tests with `superagent@9.x.x` to ensure compatibility.

### Notes

No other changes were made. All tests pass successfully.

### CODE REVIEW

**Comment by luispabon** [comment]
Thank you. Looks like the package updates aren't compatible with Node 16, which is now EOL since Oct last year or so, I'll update the build matrix on a separate PR to cover current supported versions

**Comment by luispabon** [comment]
Done & merged, please rebase & push

**Comment by kwishna** [comment]
Please publish the new npm version. `npm i superagent-retry-delay`

**Comment by luispabon** [comment]
Thanks for your contribution, this has now been published as 3.1.0

**Pull request merged**
